/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrivacyPassExample */

#ifndef _Included_PrivacyPassExample
#define _Included_PrivacyPassExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrivacyPassExample
 * Method:    brsa_context_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1context_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_secret_key_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1secret_1key_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_public_key_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1public_1key_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_message_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1blind_1message_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blinding_secret_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1blinding_1secret_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_signature_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1blind_1signature_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_signature_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_PrivacyPassExample_brsa_1signature_1new
  (JNIEnv *, jobject);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_publickey_import_spki
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1publickey_1import_1spki
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_signature_import
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1blind_1signature_1import
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_context_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1context_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_secret_key_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1secret_1key_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_public_key_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1public_1key_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_message_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1blind_1message_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blinding_secret_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1blinding_1secret_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_signature_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1blind_1signature_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_signature_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1signature_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_message_copy
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_PrivacyPassExample_brsa_1blind_1message_1copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_signature_copy
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_PrivacyPassExample_brsa_1signature_1copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_context_init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PrivacyPassExample_brsa_1context_1init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_keygen
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1keygen
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_wrapper
 * Signature: (JJJJ[B)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1blind_1wrapper
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_blind_sign_wrapper
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1blind_1sign_1wrapper
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_finalize_wrapper
 * Signature: (JJJJJ[B)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1finalize_1wrapper
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     PrivacyPassExample
 * Method:    brsa_verify
 * Signature: (JJJ[B)I
 */
JNIEXPORT jint JNICALL Java_PrivacyPassExample_brsa_1verify
  (JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
